//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.29 at 02:03:19 PM PKT 
//


package com.idev4.loans.cb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ArrayOfDefaultAddResponse complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ArrayOfDefaultAddResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DefaultAddResponse" type="{http://schemas.datacontract.org/2004/07/DataCheckEnquiry}DefaultAddResponse" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfDefaultAddResponse", propOrder = {
        "defaultAddResponse"
})
public class ArrayOfDefaultAddResponse {

    @XmlElement(name = "DefaultAddResponse", nillable = true)
    protected List<DefaultAddResponse> defaultAddResponse;

    /**
     * Gets the value of the defaultAddResponse property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the defaultAddResponse property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDefaultAddResponse().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DefaultAddResponse }
     */
    public List<DefaultAddResponse> getDefaultAddResponse() {
        if (defaultAddResponse == null) {
            defaultAddResponse = new ArrayList<DefaultAddResponse>();
        }
        return this.defaultAddResponse;
    }

}
