//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.29 at 02:03:19 PM PKT 
//


package com.idev4.loans.cb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ArrayOfDefaultUpdateResponse complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ArrayOfDefaultUpdateResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DefaultUpdateResponse" type="{http://schemas.datacontract.org/2004/07/DataCheckEnquiry}DefaultUpdateResponse" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfDefaultUpdateResponse", propOrder = {
        "defaultUpdateResponse"
})
public class ArrayOfDefaultUpdateResponse {

    @XmlElement(name = "DefaultUpdateResponse", nillable = true)
    protected List<DefaultUpdateResponse> defaultUpdateResponse;

    /**
     * Gets the value of the defaultUpdateResponse property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the defaultUpdateResponse property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDefaultUpdateResponse().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DefaultUpdateResponse }
     */
    public List<DefaultUpdateResponse> getDefaultUpdateResponse() {
        if (defaultUpdateResponse == null) {
            defaultUpdateResponse = new ArrayList<DefaultUpdateResponse>();
        }
        return this.defaultUpdateResponse;
    }

}
