//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.29 at 02:03:19 PM PKT 
//


package com.idev4.loans.cb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RCU complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RCU"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FileNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="GroupId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="HighCredit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastPayment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MaturityDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NewAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NewAccountStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NewAccountType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NewAssociationType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NewTerms" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NicNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ODBalance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OutStandingBalance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PaymentStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StatusDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TransactionNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="checkerPassword" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="checkerUserName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="controlBranchCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="makerPassword" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="makerUserName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="memberCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="subBranchCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RCU", propOrder = {
        "accountNumber",
        "amount",
        "currency",
        "fileNo",
        "groupId",
        "highCredit",
        "lastPayment",
        "maturityDate",
        "newAccountNumber",
        "newAccountStatus",
        "newAccountType",
        "newAssociationType",
        "newTerms",
        "nicNo",
        "odBalance",
        "outStandingBalance",
        "paymentStatus",
        "statusDate",
        "transactionNum",
        "checkerPassword",
        "checkerUserName",
        "controlBranchCode",
        "makerPassword",
        "makerUserName",
        "memberCode",
        "subBranchCode"
})
public class RCU {

    @XmlElementRef(name = "AccountNumber", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> accountNumber;
    @XmlElementRef(name = "Amount", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> amount;
    @XmlElementRef(name = "Currency", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> currency;
    @XmlElementRef(name = "FileNo", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> fileNo;
    @XmlElementRef(name = "GroupId", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> groupId;
    @XmlElementRef(name = "HighCredit", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> highCredit;
    @XmlElementRef(name = "LastPayment", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lastPayment;
    @XmlElementRef(name = "MaturityDate", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> maturityDate;
    @XmlElementRef(name = "NewAccountNumber", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> newAccountNumber;
    @XmlElementRef(name = "NewAccountStatus", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> newAccountStatus;
    @XmlElementRef(name = "NewAccountType", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> newAccountType;
    @XmlElementRef(name = "NewAssociationType", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> newAssociationType;
    @XmlElementRef(name = "NewTerms", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> newTerms;
    @XmlElementRef(name = "NicNo", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> nicNo;
    @XmlElementRef(name = "ODBalance", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> odBalance;
    @XmlElementRef(name = "OutStandingBalance", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> outStandingBalance;
    @XmlElementRef(name = "PaymentStatus", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> paymentStatus;
    @XmlElementRef(name = "StatusDate", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> statusDate;
    @XmlElementRef(name = "TransactionNum", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> transactionNum;
    @XmlElementRef(name = "checkerPassword", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> checkerPassword;
    @XmlElementRef(name = "checkerUserName", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> checkerUserName;
    @XmlElementRef(name = "controlBranchCode", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> controlBranchCode;
    @XmlElementRef(name = "makerPassword", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> makerPassword;
    @XmlElementRef(name = "makerUserName", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> makerUserName;
    @XmlElementRef(name = "memberCode", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> memberCode;
    @XmlElementRef(name = "subBranchCode", namespace = "http://schemas.datacontract.org/2004/07/DataCheckEnquiry", type = JAXBElement.class, required = false)
    protected JAXBElement<String> subBranchCode;

    /**
     * Gets the value of the accountNumber property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setAccountNumber(JAXBElement<String> value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the amount property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setAmount(JAXBElement<String> value) {
        this.amount = value;
    }

    /**
     * Gets the value of the currency property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setCurrency(JAXBElement<String> value) {
        this.currency = value;
    }

    /**
     * Gets the value of the fileNo property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getFileNo() {
        return fileNo;
    }

    /**
     * Sets the value of the fileNo property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setFileNo(JAXBElement<String> value) {
        this.fileNo = value;
    }

    /**
     * Gets the value of the groupId property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setGroupId(JAXBElement<String> value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the highCredit property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getHighCredit() {
        return highCredit;
    }

    /**
     * Sets the value of the highCredit property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setHighCredit(JAXBElement<String> value) {
        this.highCredit = value;
    }

    /**
     * Gets the value of the lastPayment property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getLastPayment() {
        return lastPayment;
    }

    /**
     * Sets the value of the lastPayment property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setLastPayment(JAXBElement<String> value) {
        this.lastPayment = value;
    }

    /**
     * Gets the value of the maturityDate property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getMaturityDate() {
        return maturityDate;
    }

    /**
     * Sets the value of the maturityDate property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setMaturityDate(JAXBElement<String> value) {
        this.maturityDate = value;
    }

    /**
     * Gets the value of the newAccountNumber property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getNewAccountNumber() {
        return newAccountNumber;
    }

    /**
     * Sets the value of the newAccountNumber property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setNewAccountNumber(JAXBElement<String> value) {
        this.newAccountNumber = value;
    }

    /**
     * Gets the value of the newAccountStatus property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getNewAccountStatus() {
        return newAccountStatus;
    }

    /**
     * Sets the value of the newAccountStatus property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setNewAccountStatus(JAXBElement<String> value) {
        this.newAccountStatus = value;
    }

    /**
     * Gets the value of the newAccountType property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getNewAccountType() {
        return newAccountType;
    }

    /**
     * Sets the value of the newAccountType property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setNewAccountType(JAXBElement<String> value) {
        this.newAccountType = value;
    }

    /**
     * Gets the value of the newAssociationType property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getNewAssociationType() {
        return newAssociationType;
    }

    /**
     * Sets the value of the newAssociationType property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setNewAssociationType(JAXBElement<String> value) {
        this.newAssociationType = value;
    }

    /**
     * Gets the value of the newTerms property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getNewTerms() {
        return newTerms;
    }

    /**
     * Sets the value of the newTerms property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setNewTerms(JAXBElement<String> value) {
        this.newTerms = value;
    }

    /**
     * Gets the value of the nicNo property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getNicNo() {
        return nicNo;
    }

    /**
     * Sets the value of the nicNo property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setNicNo(JAXBElement<String> value) {
        this.nicNo = value;
    }

    /**
     * Gets the value of the odBalance property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getODBalance() {
        return odBalance;
    }

    /**
     * Sets the value of the odBalance property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setODBalance(JAXBElement<String> value) {
        this.odBalance = value;
    }

    /**
     * Gets the value of the outStandingBalance property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getOutStandingBalance() {
        return outStandingBalance;
    }

    /**
     * Sets the value of the outStandingBalance property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setOutStandingBalance(JAXBElement<String> value) {
        this.outStandingBalance = value;
    }

    /**
     * Gets the value of the paymentStatus property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * Sets the value of the paymentStatus property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setPaymentStatus(JAXBElement<String> value) {
        this.paymentStatus = value;
    }

    /**
     * Gets the value of the statusDate property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getStatusDate() {
        return statusDate;
    }

    /**
     * Sets the value of the statusDate property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setStatusDate(JAXBElement<String> value) {
        this.statusDate = value;
    }

    /**
     * Gets the value of the transactionNum property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getTransactionNum() {
        return transactionNum;
    }

    /**
     * Sets the value of the transactionNum property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setTransactionNum(JAXBElement<String> value) {
        this.transactionNum = value;
    }

    /**
     * Gets the value of the checkerPassword property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getCheckerPassword() {
        return checkerPassword;
    }

    /**
     * Sets the value of the checkerPassword property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setCheckerPassword(JAXBElement<String> value) {
        this.checkerPassword = value;
    }

    /**
     * Gets the value of the checkerUserName property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getCheckerUserName() {
        return checkerUserName;
    }

    /**
     * Sets the value of the checkerUserName property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setCheckerUserName(JAXBElement<String> value) {
        this.checkerUserName = value;
    }

    /**
     * Gets the value of the controlBranchCode property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getControlBranchCode() {
        return controlBranchCode;
    }

    /**
     * Sets the value of the controlBranchCode property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setControlBranchCode(JAXBElement<String> value) {
        this.controlBranchCode = value;
    }

    /**
     * Gets the value of the makerPassword property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getMakerPassword() {
        return makerPassword;
    }

    /**
     * Sets the value of the makerPassword property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setMakerPassword(JAXBElement<String> value) {
        this.makerPassword = value;
    }

    /**
     * Gets the value of the makerUserName property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getMakerUserName() {
        return makerUserName;
    }

    /**
     * Sets the value of the makerUserName property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setMakerUserName(JAXBElement<String> value) {
        this.makerUserName = value;
    }

    /**
     * Gets the value of the memberCode property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getMemberCode() {
        return memberCode;
    }

    /**
     * Sets the value of the memberCode property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setMemberCode(JAXBElement<String> value) {
        this.memberCode = value;
    }

    /**
     * Gets the value of the subBranchCode property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getSubBranchCode() {
        return subBranchCode;
    }

    /**
     * Sets the value of the subBranchCode property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setSubBranchCode(JAXBElement<String> value) {
        this.subBranchCode = value;
    }

}
